[package]
name = "timerunner"
version = "0.1.0"
authors = ["Southclaws <southclawjk@gmail.com>"]

[dependencies]
iron = "0.6.0"
uuid = { version = "0.6", features = ["v4"] }
time = "*"
dotenv = "0.13.0"
